name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - azureml-inference-server-http
      - cloudpickle==2.2.0
      - psutil==5.8.0
      - scikit-learn>=1.0.0